# Linguistic Data Organisation with Python
One of the many various advantages why applied linguists and data scientists prefer Python alike is ita abundance of rich frameworks and libraries designed by numerous engineers and thoroughly tested. Some of them, in particular **Numpy**, **Pandas** and **Matplotlib** form a famous trio of data arrangement and visualisation, which far exceeds GUI-based applications such as Google Spreadsheets. In this notebook, you will learn about what Pythonic libraries draw the best data management practices in a simple and comprehensible way.

# NumPy
The first and simplest one is the library used to process numeric data and advanced math operations. *NumPy* is a library that pairs simplicity and flexibility of Python with C-backed primitive lightweight numeric constraints and allows developers generate true arrays of integers or floating-point numbers the same way as in C. This package is primarily concerned with boosting performance with aid of homogenous arrays and performing mathematical operations on them.   

## Array initialisation
Making an array in NumPy is as easy as calling its `array()` method and passing a Pythonic list.

In [1]:
import numpy as np
#Create an array with a list:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#Create an array with a range:
range = np.arange(1, 21, 2)
#Create an hollow array:
hollow = np.empty(10) #np.zeros() or np.ones() are also options
print(type(array), type(range), type(hollow))
print(array)
print(range)
print(hollow)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
[6.91045040e-310 6.91045040e-310 4.37003813e-310 3.10551199e-271
 3.78576768e-270 1.37189170e-231 1.08642527e-202 4.26638929e-270
 4.04086635e-270 4.02793032e-270]


As we can see, all true arrays in Python are treated as objects of the `numpy.ndarray` (n-dimensional) classes. In similar way to lists, they hold a sequence of values, however what makes them powerful is that:
1. arrays are fixed-size, they cannot have cells inserted or removed once initialised;
2. arrays are always homogenous, which means they can only store values of the same type;
3. Numpy opens a way to use primitive values, since in Python everything is objects.

## Array modification
NumPy allows developers to generate arrays out of existing iterables, generators, create an empty or array filled with zeroes or ones initially. Because arrays are fixed, items cannot be inserted or deleted from them, however it's possible to generate new arrays that copy all of the previous items with specified changes, similarly to C++ `std::vector`. 

In [3]:
#Modifying arrays. Notice a new array is generated each time, and we point 
#the variable to the new array so that the old one is garbage collected.
array = np.append(array, 11)
array = np.insert(array, 0, 0)
array = np.delete(array, 3)
print(array)

[ 0  1  2  4  5  6  7  8  9 10 11 11]


## Multidimensional arrays
Arrays are not just chains of values, but it is possible to extend them into multiple dimensions. NumPy was specifically designed to handle them efficiently. All of the operations described before are applicable to them too.

In [9]:
#Accessing array values and slicing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
rowSlice = matrix[0]
columnSlice = matrix[:, 0]
print(rowSlice)
print(columnSlice)
print("~~~~~")
#Accessing elements with a range:
rowSliceShortened   = matrix[0, 0:2]
columnSliceShortned = matrix[0:2, 0]
print(rowSliceShortened)
print(columnSliceShortned)
print("~~~~~")
#Accessing elements with a list:
rowListSlice    = matrix[0, [0, 2]] #Get the first and third elements of the first row
columnListSlice = matrix[[0, 2], 0] #Get the first and third elements of the first column
print(rowListSlice)
print(columnListSlice)
print("~~~~~")
#Accessing elements with a boolean array:
rowBoolSlice    = matrix[0, [True, False, True]] #Get the first and third elements of the first row
columnBoolSlice = matrix[[False, False, True], 0] #Get the last element of the first column
print(rowBoolSlice)
print(columnBoolSlice)
print("~~~~~")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
~~~~~
[1 2]
[1 4]
~~~~~
[1 3]
[1 7]
~~~~~
[1 3]
[1 7]


All operators apply the operation to all array values. For example, an expression like `array * 5` will generate a new array whose all values are multiplied by 5.

In [10]:
# Aray operations
added      = array + 1
subtracted = array - 1
multiplied = array * 2
divided    = array / 2
print(added)
print(subtracted)
print(multiplied)
print(divided)


[ 1  2  3  5  6  7  8  9 10 11 12 12]
[-1  0  1  3  4  5  6  7  8  9 10 10]
[ 0  2  4  8 10 12 14 16 18 20 22 22]
[0.  0.5 1.  2.  2.5 3.  3.5 4.  4.5 5.  5.5 5.5]


## Array types
NumPy comes with the built-in primitive datatypes that date back to the origin of computer science and lie in the foundation of ancient languages, such as C, Fortran or APL. 

In [16]:
integers = np.zeros(10, dtype=np.int32) 
floats   = np.zeros(10, dtype=np.float32)
print(integers)
print(floats)

try: 
    integers[0] = 17.5 #Assign a floating point number to an integer array
    floats[0] = 56 #Assign an integer to a floating point array
except ValueError as e:
    print(e)
print(integers)
print(floats)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[17  0  0  0  0  0  0  0  0  0]
[56.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Bad pipe message: %s [b'\x02\xbb\xca/\xfc\xe0\x9f\x14\xfb\xf5\x02P\xc3\xfc\x85\xf3\x7fV \xaf\x7f\x10\x80\x11:\x14F\x1eF\xceF\xf1v\xbc\x97Z\x89\xd9Pr\xdf:S\xfc\xbd\x0b8\xed\xf6q%\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00', b'\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01']
Bad pipe message: %s [b"\xc1}+\x86\x1b\xb5\xfb\xaa\x8a\x87\x96K\xdb\x9b\x18\x99\xef\xb0\x00\x00|\xc0,\xc00\x00\xa3\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0\xaf\xc0\xad\xc0\xa3\xc0\x9f\xc0]\xc0a\xc0W\xc0S\xc0+\xc0/\x00\xa2\x00\x9e\xc0\xae\xc0\xac\xc0\xa2\xc0\x9e\xc0\\\xc0`\xc0V\xc0R\xc0$\xc0(\x00k\x00j\xc0#\xc0'\x00g\x00@\xc0\n\xc0\x14\x009\x008\xc0\t\xc0\x13\x003\x002\x00\x9d\xc0\xa1\xc0\x9d\xc0Q\x00\x9c\xc0\xa0\xc0\x9c\xc0P\x00=\x00<\x005\x00/\x00\x9a\x00\x

As we can see, NumPy automatically casts given value into the array's respective type and does not raise any error in inherent for C manner. Aside from those, these types are also available (with C equivalents in parentheses):
* `numpy.bool_` (bool) boolean (true or false) bytes;
* `numpy.byte` (singed char), `.ubyte` (unsigned char), `.intc` (int), `.short` (short), `.int_` (long), `.longlong` (long long), `.ulonglong` (unsigned long long) are all platform-specific;
* `numpy.half`/`.float16` half precision floating-point: 5 bit exponent, 10 bits mantissa;
* `numpy.single` (float) single precision floating-point number, typically 8 bit exponent and 23 bit mantissa;
* `numpy.double` (double), `.longdouble` (long double) double presision floating-point number: 11 bit exponent, 52 bit mantissa;
* `numpy.cdouble` (double complex), `.csingle` complex number represented as real and imaginary components with two double/single precision values;
* `numpy.string_` (char*) string texts.

When the arrays are defined with a specific type, the range of operations available for them significantly decreases and may cause certain exceptions at the runtime as it is inherent for a dynamically-typed language. In Python, not every value can even be remotely known at the stage of development, therefore this issue is addressed with the special `numpy.object` type. Under the hood, it sacrifices possible performance gains array usage brings over lists for the purpose of flexibility by storing in the array not the actual values but pointers to respective Python objects. At this point, they differ from original Python lists really little and excessive insertion and deletion leads to making arrays entirely obsolete.  
_Conclusion: Don't expect a dynamic interpreted language to be safe or performant, use Go instead._